### ISSUE TITLE
Pyenv/Python version trouble 

### ISSUE THREAD

**Issue by JohnMalagise** [Allegheny-Computer-Science-302-F2020/cs302-F2020-plans#3]
**The global command to switch python versions within pyenv does not work**

When I try to change my python version to 3.8 using pyenv, nothing happens.
~$ pyenv global 3.8.0
my python version is still 2.7.17 and my python3 version is 3.6.9

**Explain the steps you have taken so Far**

Steps to taken so far in an attempt to resolve the issue:

- Uninstall pyenv and reinstall
- Install python from different sources
- Googled how to fix the problem
- Tried installing versions of python using pip3
- Tried installing versions from pythons website
- Tried using "local" instead of "global"

**Explain the expected behavior**

I need my python version to be changed to 3.8.0 before I can even begin my lab.
I think the issue is which version the word "python" points to. I cannot seem to get python or python3 to point to the version installed by pyenv

**Explain your execution environment**

I use a lenovo yoga 730 running the latest (stable) release of Ubuntu.

**Explain the timeline by which you need to have this issue resolved**

I need this resolved ASAP, at least before the lab is due

**Give the name of at least two members of the course who are willing to
partner with you to help you to resolve this issue**

NA
**Provide any additional context**

**Comment by gkapfham** [comment]
Hello @JohnMalagise thanks for reporting this issue, your efforts are greatly appreciated! If my records are correct, you solved this problem by following instructions like those that are available at this web site:

https://docs.python-guide.org/starting/install3/linux/

If you are still running into problems, can you please document them here? If you think that this issue was fully resolved, can you write a summary to indicate what you did to solve it? In this case, you might want to paste the note that you added to slack also here as a comment, thereby ensuring that others can learn from our experiences and new knowledge! Thanks!

**Comment by gkapfham** [comment]
Hi @JohnMalagise can you please confirm n that this issue is resolved and then close the issue if it is?
